@startuml EditProfile

actor User as "Users"
boundary "Profile Page" as View 
participant ":authRoute" as Route 
control "authMiddleware" as Auth 
control "authController" as Controller 
participant ":authService" as Service 
entity "userModel" as Model 
database "MongoDB" as MongoDB
hide footbox

User -> View: 1. Click "Edit"
activate View
activate User
User -> View: 2. Edit avatar, gender, height, weight, dob.

View -> View: 3. Validate input
activate View
deactivate View

opt Invalid input
    View --> User: 3.1. Display "Invalid input information"
end

View -> Route: 4. POST /api/v1/auth/profile
activate Route
Route -> Auth: 5. authenticateUser(req, res, next)
activate Auth
ref over User, MongoDB : Verifies token

Auth -> Controller: 6. next(req)
deactivate Auth
activate Controller

    Controller -> Service: 7. findByIdAndUpdate(userId, profileData)
    activate Service

    Service -> Model: 8. editUserById(userId, profileData)
    activate Model

    Model -> MongoDB: 9. ExecuteQuery()
    activate MongoDB
    MongoDB --> Model: 10. Return result
    deactivate MongoDB

    Model --> Service: 11. Return update result
    deactivate Model

    Service -> Service: 12. checkUpdateProfile()
    activate Service
    deactivate Service

alt Update Failed
    Service --> Controller: 12.1. Return error
    Controller --> Route: 12.1.1 Return error info
    Route --> View: 12.1.2. Show "Update failed"
    View --> User: 12.1.3. Display error message
else Update Success
    Service --> Controller: 12.2. Return success
    deactivate Service
    Controller --> Route: 12.2.1. Return success
    deactivate Controller
    Route --> View: 12.2.2. Return success
    deactivate Route
    View --> User: 12.2.3. Display updated profile
    deactivate View
    deactivate User
end
@enduml
