'use client';
import { createContext, useContext, useState } from 'react';

const translations = {
	vi: {
		// Profile Page
		profile_title: 'Hồ sơ tài khoản',
		profile_subtitle: 'Quản lý thông tin và bảo mật tài khoản.',
		avatar_title: 'Ảnh đại diện',
		upload_photo: 'Tải ảnh lên',
		file_hint: 'PNG/JPG, tối đa 5MB.',
		account_info: 'Thông tin tài khoản',
		created_at: 'Ngày tạo tài khoản',
		save_changes: 'Lưu thay đổi',
		saving: 'Đang lưu...',
		change_password: 'Đổi mật khẩu',
		current_password: 'Mật khẩu hiện tại',
		new_password: 'Mật khẩu mới',
		confirm_password: 'Nhập lại',
		change_password_btn: 'Đổi mật khẩu',
		changing: 'Đang đổi...',
		loading_profile: 'Đang tải hồ sơ...',
		not_logged_in: 'Chưa đăng nhập.',
		no_image: 'Không có hình ảnh',
		placeholder_full_name: 'Nhập họ và tên',
		placeholder_phone: 'Nhập số điện thoại',
		err_select_image: 'Vui lòng chọn file hình ảnh',
		err_image_too_large: 'Ảnh quá lớn (tối đa 5MB)',
		err_read_image: 'Không đọc được file ảnh',
		err_full_name_required: 'Họ và tên không được để trống',
		err_phone_required: 'Số điện thoại không được để trống',
		err_full_name_and_phone_required:
			'Vui lòng nhập họ và tên và số điện thoại',
		err_phone_min10: 'Số điện thoại phải có ít nhất 10 chữ số',
		err_payload_too_large:
			'Dữ liệu gửi lên quá lớn. Vui lòng chọn ảnh nhỏ hơn.',
		profile_updated: 'Cập nhật hồ sơ thành công',
		profile_update_failed: 'Cập nhật hồ sơ thất bại',
		pw_required: 'Vui lòng nhập đủ mật khẩu',
		pw_policy:
			'Mật khẩu mới phải có ít nhất 12 ký tự, gồm chữ hoa, chữ thường, số và ký tự đặc biệt (@, #, $, *)',
		pw_mismatch: 'Mật khẩu mới không khớp',
		pw_changed: 'Đổi mật khẩu thành công',
		pw_change_failed: 'Đổi mật khẩu thất bại',

		// Header
		welcome: 'Chào mừng trở lại, Admin!',
		overview: 'Tổng quan hoạt động hệ thống VietDurian',
		logout: 'Đăng xuất',

		// Sidebar
		dashboard: 'Bảng điều khiển',
		users: 'Người dùng',
		gardens: 'Vườn sầu riêng',
		products: 'Sản phẩm',
		posts: 'Bài viết',
		blogs: 'Blog',
		moderation: 'Kiểm duyệt',
		settings: 'Cài đặt',
		search_product: 'Tìm kiếm tên sản phẩm...',
		manage_products: 'Quản lý sản phẩm',
		all_types: 'Tất cả loại',
		rating_high_to_low: 'Đánh giá: Cao - thấp',
		rating_low_to_high: 'Đánh giá: Thấp đến cao',
		price: 'Giá',
		filter_product: 'Lọc sản phẩm',
		rating_product: 'Đánh giá: Cao đến Thấp',
		type_product: 'Loại sản phẩm',

		// Stats
		total_platform_users: 'Tổng số người dùng nền tảng',
		experts: 'Chuyên gia',
		total_posts: 'Tổng số bài Post',
		total_blogs: 'Tổng số bài Blog',
		vs_last_month: 'so với tháng trước',

		// Posts
		post_management: 'Quản lý bài viết',
		content: 'Nội dung',
		description: 'Mô tả',
		category: 'Thể loại',
		inactive_post: 'Đưa về trạng thái Ngưng hoạt động',
		active_post: 'Đưa về trạng thái Hoạt động',
		delete_post: 'Xóa bài viết',
		service_type: 'Loại dịch vụ',
		close: 'Đóng',
		image: 'Hình ảnh',
		contact: 'Liên hệ',
		showing_range: 'Hiển thị',
		no_posts: 'Không có bài viết nào',

		// Charts
		market_trend: 'Xu hướng thị trường sầu riêng',
		price_volume: 'Giá trung bình và khối lượng trung bình',
		role_distribution_title: 'Phân bố người dùng theo vai trò',
		role_distribution_subtitle: 'Số lượng người dùng theo từng vai trò',
		post_blog_trend_title: 'Xu hướng Post & Blog',
		post_blog_trend_subtitle: 'Số lượng theo thời gian',
		garden_distribution: 'Bản đồ phân bổ vườn sầu riêng',
		track_coordinates: 'Theo dõi tọa độ và diện tích vườn trên toàn quốc',
		avg_price: 'Giá trung bình',
		volume: 'Khối lượng',
		area: 'Diện tích',
		total: 'Tổng',
		count_users: 'Số người dùng',

		// Control Center
		permission_requests: 'Yêu cầu duyệt quyền',
		manage_users: 'Quản lý tài khoản người dùng',
		reported_posts: 'Báo cáo vi phạm',
		content_moderation: 'Kiểm duyệt nội dung bài viết',
		view_all: 'Xem tất cả',
		view_details: 'Xem chi tiết',
		view_detail: 'Xem chi tiết',

		// Product rating page
		product_ratings: 'Đánh giá sản phẩm',
		manage_product_ratings: 'Danh sách sản phẩm sắp xếp theo đánh giá từ cao đến thấp',
		no_products: 'Không có sản phẩm',
		rating: 'Đánh giá',
		out_of_5: 'trên 5',
		list: 'Danh sách',
		failed_to_load_products: 'Không thể tải danh sách sản phẩm',

		// Users Page
		user_management: 'Quản lý người dùng',
		search_users: 'Tìm kiếm người dùng...',
		all_roles: 'Tất cả vai trò',
		all_status: 'Tất cả trạng thái',
		farmer: 'Nông dân',
		trader: 'Thương lái',
		serviceProvider: 'Nhà cung cấp dịch vụ',
		contentExpert: 'Chuyên gia nội dung',
		admin: 'Quản trị viên',
		unknown: 'Không xác định',
		expert: 'Chuyên gia',
		business: 'Doanh nghiệp',
		active: 'Hoạt động',
		inactive: 'Ngưng hoạt động',
		pending: 'Chờ duyệt',
		name: 'Họ tên',
		email: 'Email',
		phone: 'Số điện thoại',
		role: 'Vai trò',
		status: 'Trạng thái',
		actions: 'Thao tác',
		edit: 'Sửa',
		delete: 'Xóa',
		approve: 'Duyệt',
		reject: 'Từ chối',
		block: 'Chặn',
		unblock: 'Bỏ chặn',
		blocked: 'Đã chặn',
		block_user: 'Chặn người dùng',
		unblock_user: 'Bỏ chặn người dùng',
		block_confirm: 'Bạn có chắc chắn muốn chặn người dùng này?',
		unblock_confirm: 'Bạn có chắc chắn muốn bỏ chặn người dùng này?',
		block_description: 'Người dùng sẽ không thể đăng nhập và sử dụng hệ thống.',
		unblock_description:
			'Người dùng sẽ có thể đăng nhập và sử dụng hệ thống trở lại.',
		cancel: 'Hủy',
		confirm: 'Xác nhận',
		success: 'Thành công',
		user_blocked: 'Đã chặn người dùng thành công',
		user_unblocked: 'Đã bỏ chặn người dùng thành công',
		error_fetching_users: 'Không thể tải danh sách người dùng',
		error_updating_user_status: 'Không thể cập nhật trạng thái người dùng',
		no_users_found: 'Không tìm thấy người dùng',
		error_fetching_user_detail: 'Không thể tải thông tin người dùng',
		location: 'Địa chỉ',
		join_date: 'Ngày tham gia',
		user_detail_no_name: 'Chưa có tên',
		user_detail_account_overview: 'Tổng quan tài khoản',
		user_detail_account_overview_desc:
			'Bảng này cung cấp thông tin tổng quan nhanh về tài khoản người dùng đã chọn, bao gồm trạng thái hồ sơ và thông tin quan trọng.',
		user_detail_member_since: 'Thành viên từ',
		user_detail_updating: 'Đang cập nhật...',
		user_detail_no_data: 'Không có dữ liệu',
		user_detail_personal_information: 'Thông tin cá nhân',
		user_detail_review_description: 'Xem chi tiết thông tin tài khoản của người dùng đã chọn.',
		user_detail_no_user_data: 'Không có dữ liệu người dùng.',

		// Status labels
		Pending: 'Chờ duyệt',
		Resolved: 'Đã xử lý',

		// Priority
		high: 'Cao',
		medium: 'Trung bình',
		low: 'Thấp',

		// page
		to: 'đến',
		of: 'trên',
		page: 'Trang',

		// Delete Post Modal
		delete_post_title: 'Xóa bài viết',
		delete_post_message: 'Bạn có chắc chắn muốn xóa bài viết này?',

		// postRequests
		postRequests: 'Yêu cầu bài viết',
		search_posts: 'Tìm kiếm bài viết...',
		reject_post: 'Từ chối bài viết',
		reject_post_message: 'Bạn có chắc chắn muốn từ chối bài viết này?',
		enter_reason: 'Nhập lý do từ chối...',
		post_approved_success: 'Duyệt bài viết thành công',
		post_rejected_success: 'Từ chối bài viết thành công',
		reject_button: 'Từ chối',
		progressing: 'Đang xử lý',

		// Reports Page
		reports: 'Báo cáo',
		title_report: 'Nội dung bài viết',
		manage_reports: 'Xử lý các báo cáo vi phạm từ người dùng',
		search_reports: 'Tìm theo nội dung bài viết...',
		reporter: 'Người báo cáo',
		reason: 'Lý do',
		report_image: 'Hình ảnh',
		time: 'Thời gian',
		resolve: 'Xử lí',
		resolved: 'Đã xử lý',
		completed: 'Đã hoàn thành',
		newest: 'Mới nhất',
		oldest: 'Cũ nhất',
		sort_date: 'Ngày',
		sort_name: 'Tên',
		report_resolved: 'Đã xử lý báo cáo thành công',
		report_resolved_desc: 'Báo cáo đã được đánh dấu là đã hoàn thành',
		confirm_delete_title: 'Xác nhận xóa',
		confirm_delete_desc: 'Bạn có chắc muốn xóa báo cáo này?',
		no_image: 'Không có hình ảnh',
		no_reports_found: 'Không tim thấy báo cáo',
		report_post: 'Bài viết',
		report_comment: 'Bình luận',
		ban_confirm_comment: 'Bạn có chắc chắn muốn khoá bình luận này?',
		ban_success: 'Bình luận đã bị khoá',
		hide: 'Ẩn bình luận',
		hide_confirm_comment:
			'Bạn có chắc chắn muốn ẩn bình luận này và đánh dấu báo cáo là đã xử lý?',
		hide_success: 'Bình luận đã được ẩn',
		hide_and_resolved_success:
			'Bình luận đã được ẩn và báo cáo đã được đánh dấu là đã xử lý',
		report_status_updated: 'Cập nhật trạng thái thành công',
		no_reports: 'Không có báo cáo',

		// blogs
		author: 'Họ tên tác giả',
		title: 'Tiêu đề',
		manage_blogs: 'Quản lý bài viết kiến thức',
		search_blogs: 'Tìm kiếm blog...',
		confirm_delete_blog: 'Bạn có chắc chắn muốn xóa blog này?',
		delete_warning: 'Hành động này không thể hoàn tác!',

		// stages
		stages: 'Giai đoạn',
		stage_management: 'Quản lý giai đoạn',
		stage_subtitle: 'Tạo, sửa, tìm kiếm và sắp xếp các giai đoạn.',
		stage_sort_time: 'Sắp xếp theo thời gian',
		stage_add: 'Thêm giai đoạn',
		stage_update: 'Cập nhật giai đoạn',
		stage_modal_hint: 'Nhập tiêu đề và mô tả cho giai đoạn.',
		stage_title: 'Tiêu đề',
		stage_description: 'Mô tả',
		stage_title_placeholder: 'Nhập tiêu đề giai đoạn',
		stage_description_placeholder: 'Mô tả chi tiết giai đoạn',
		stage_time: 'Thời gian',
		stage_order: 'STT',
		stage_search_placeholder: 'Tìm kiếm theo tiêu đề hoặc mô tả',
		stage_confirm_delete: 'Bạn có chắc chắn muốn xóa giai đoạn này?',
		stage_delete_success: 'Đã xóa giai đoạn',
		stage_delete_fail: 'Không thể xóa giai đoạn',
		stage_delete_note: 'Hành động này sẽ xóa giai đoạn khỏi danh sách.',
		stage_create_success: 'Đã tạo giai đoạn mới',
		stage_update_success: 'Đã cập nhật giai đoạn',
		stage_fetch_fail: 'Không thể tải danh sách giai đoạn',
		stage_action_fail: 'Thao tác không thành công',
		stage_title_required: 'Vui lòng nhập tiêu đề giai đoạn',
		stage_description_required: 'Vui lòng nhập mô tả giai đoạn',
		loading: 'Đang tải...',
		checking: 'Đang kiểm tra...',
		no_data: 'Không có dữ liệu',

		//type
		types: 'Phân Loại',
		product_types: 'Loại sầu riêng',
		manage_product_types: 'Quản lý các loại sầu riêng',
		add_product_type: 'Thêm loại sầu riêng',
		product_type: 'Loại sầu riêng',
		description: 'Mô tả',
		created_date: 'Ngày tạo',
		no_description: 'Chưa có mô tả',
		no_product_types: 'Không có loại sầu riêng nào',
		search_product_types: 'Tìm theo tên loại sầu riêng, mô tả...',
		enter_product_type_name: 'Nhập tên loại sầu riêng',
		product_type_name: 'Tên loại sầu riêng',
		enter_description: 'Nhập mô tả',
		type_description_template: 'Nguồn gốc: ...\nĐặc điểm: ...\nƯu điểm: ...\nThời gian thu hoạch: ...',
		edit_product_type: 'Chỉnh sửa loại sầu riêng',
		confirm_delete_product_type: 'Bạn có chắc muốn xóa loại sầu riêng này?',
		create: 'Tạo',
		creating: 'Đang tạo...',
		update: 'Cập nhật',
		updating: 'Đang cập nhật...',
		deleting: 'Đang xóa...',
		unknown_date: 'Chưa có thông tin',
		invalid_date: 'Ngày không hợp lệ',
		type_name_required: 'Tên loại sầu riêng không được để trống',
		type_name_duplicate: 'Tên loại sầu riêng đã tồn tại',
		type_description_required: 'Mô tả không được để trống',
		create_type_success: 'Tạo loại sầu riêng thành công',
		create_type_failed: 'Tạo loại sầu riêng thất bại',
		update_type_success: 'Cập nhật loại sầu riêng thành công',
		update_type_failed: 'Cập nhật loại sầu riêng thất bại',
		delete_type_success: 'Xóa loại sầu riêng thành công',
		delete_type_failed: 'Xóa loại sầu riêng thất bại',
		fetch_type_failed: 'Lấy danh sách loại sầu riêng thất bại',
		// Pagination
		page: 'Trang',
		previous: 'Trước',
		next: 'Sau',

		// Phone validation
		phone_error_required: 'Vui lòng nhập số điện thoại',
		phone_error_invalid: 'Số điện thoại không hợp lệ (phải có 10 số, bắt đầu bằng 03, 05, 07, 08, 09)',

		// Password rules display
		profile_pw_rules_title: 'Yêu cầu mật khẩu:',
		profile_pw_rule1: 'Ít nhất 12 ký tự',
		profile_pw_rule2: 'Có chữ in hoa',
		profile_pw_rule3: 'Có chữ thường',
		profile_pw_rule4: 'Có ít nhất một số',
		profile_pw_rule5: 'Có ký tự đặc biệt (ví dụ: @, #, $)',

		// Password feedback
		profile_pw_match: 'Mật khẩu khớp',
		profile_pw_not_match: 'Mật khẩu không khớp',
		profile_pw_same_as_current: 'Mật khẩu mới không được trùng mật khẩu hiện tại',

		// Password error messages from server
		profile_pw_wrong_current: 'Mật khẩu hiện tại không đúng!',
		profile_pw_invalid_new: 'Mật khẩu mới không hợp lệ!',
		profile_pw_server_error: 'Lỗi server! Vui lòng thử lại sau.',
	},
	en: {
		// Profile Page
		profile_title: 'Account Profile',
		profile_subtitle: 'Manage account information and security.',
		avatar_title: 'Avatar',
		upload_photo: 'Upload photo',
		file_hint: 'PNG/JPG, up to 5MB.',
		account_info: 'Account Information',
		created_at: 'Account created',
		save_changes: 'Save changes',
		saving: 'Saving...',
		change_password: 'Change password',
		current_password: 'Current password',
		new_password: 'New password',
		confirm_password: 'Confirm',
		change_password_btn: 'Change password',
		changing: 'Changing...',
		loading_profile: 'Loading profile...',
		not_logged_in: 'Not logged in.',
		no_image: 'No image',
		placeholder_full_name: 'Enter full name',
		placeholder_phone: 'Enter phone number',
		err_select_image: 'Please select an image file',
		err_image_too_large: 'Image is too large (max 5MB)',
		err_read_image: 'Could not read the image file',
		err_full_name_required: 'Full name is required',
		err_phone_required: 'Phone number is required',
		err_full_name_and_phone_required: 'Full name and phone number are required',
		err_phone_min10: 'Phone number must be at least 10 digits',
		err_payload_too_large:
			'Upload payload is too large. Please choose a smaller image.',
		profile_updated: 'Profile updated successfully',
		profile_update_failed: 'Failed to update profile',
		pw_required: 'Please enter both passwords',
		pw_policy:
			'New password must be at least 12 characters and include uppercase, lowercase, number, and a special character (@, #, $, *)',
		pw_mismatch: 'New passwords do not match',
		pw_changed: 'Password changed successfully',
		pw_change_failed: 'Failed to change password',

		// Header
		welcome: 'Welcome back, Admin!',
		overview: 'VietDurian System Overview',
		logout: 'Logout',

		// Sidebar
		dashboard: 'Dashboard',
		users: 'Users',
		gardens: 'Durian Gardens',
		products: 'Products',
		posts: 'Posts',
		blogs: 'Blogs',
		moderation: 'Moderation',
		settings: 'Settings',

		// Stats
		total_platform_users: 'Total number of platform users ',
		experts: 'Experts',
		total_posts: 'Total Posts',
		total_blogs: 'Total Blogs',
		vs_last_month: 'vs last month',

		// Posts
		post_management: 'Post Management',
		search_posts: 'Search posts...',
		content: 'Content',
		description: 'Description',
		category: 'Category',
		inactive_post: 'Set to Inactive',
		active_post: 'Set to Active',
		delete_post: 'Delete Post',
		service_type: 'Service Type',
		close: 'Close',
		image: 'Image',
		contact: 'Contact',
		no_posts: 'No posts found',

		// Charts
		market_trend: 'Durian Market Trend',
		price_volume: 'Average price and average kg',
		role_distribution_title: 'User Distribution by Role',
		role_distribution_subtitle: 'Number of users per role',
		post_blog_trend_title: 'Posts & Blogs Trend',
		post_blog_trend_subtitle: 'Count over time',
		garden_distribution: 'Durian Garden Distribution Map',
		track_coordinates: 'Track garden coordinates and area nationwide',
		avg_price: 'Average Price',
		volume: 'Volume',
		area: 'Area',
		total: 'Total',
		count_users: 'Users',

		// Control Center
		permission_requests: 'Permission Requests',
		manage_users: 'Manage user accounts',
		reported_posts: 'Reported Posts',
		content_moderation: 'Content moderation',
		view_all: 'View all',
		view_details: 'View details',
		view_detail: 'View detail',

		// Product rating widget
		product_ratings: 'Product ratings',
		manage_product_ratings: 'Products sorted by rating from high to low',
		no_products: 'No products',
		rating: 'Rating',
		out_of_5: 'out of 5',
		list: 'List',
		failed_to_load_products: 'Failed to load products',
		search_product: 'Search product name...',
		manage_products: 'Manage products',
		all_types: 'All Types',
		rating_high_to_low: 'Rating: High to Low',
		rating_low_to_high: 'Rating: Low to High',
		price: 'Price',
		filter_product: 'Filter products',
		rating_product: 'PRating: High to Low',
		type_product: 'Type of product',

		// Users Page
		user_management: 'User Management',
		search_users: 'Search users...',
		all_roles: 'All roles',
		all_status: 'All status',
		farmer: 'Farmer',
		trader: 'Trader',
		serviceProvider: 'Service Provider',
		contentExpert: 'Content Expert',
		admin: 'Admin',
		unknown: 'Unknown',
		expert: 'Expert',
		business: 'Business',
		active: 'Active',
		inactive: 'Inactive',
		pending: 'Pending',
		name: 'Full name',
		email: 'Email',
		phone: 'Phone number',
		role: 'Role',
		status: 'Status',
		actions: 'Actions',
		edit: 'Edit',
		delete: 'Delete',
		approve: 'Approve',
		reject: 'Reject',
		block: 'Block',
		unblock: 'Unblock',
		blocked: 'Blocked',
		block_user: 'Block User',
		unblock_user: 'Unblock User',
		block_confirm: 'Are you sure you want to block this user?',
		unblock_confirm: 'Are you sure you want to unblock this user?',
		block_description: 'User will not be able to login and use the system.',
		unblock_description: 'User will be able to login and use the system again.',
		cancel: 'Cancel',
		confirm: 'Confirm',
		success: 'Success',
		user_blocked: 'User blocked successfully',
		user_unblocked: 'User unblocked successfully',
		error_fetching_users: 'Failed to load users',
		error_updating_user_status: 'Failed to update user status',
		no_users_found: 'No users found',
		error_fetching_user_detail: 'Unable to load user details',
		location: 'Location',
		join_date: 'Join Date',
		user_detail_no_name: 'No Name',
		user_detail_account_overview: 'Account Overview',
		user_detail_account_overview_desc:
			'This panel provides a quick overview of the selected user account, including profile status and essential information.',
		user_detail_member_since: 'Member Since',
		user_detail_updating: 'Updating...',
		user_detail_no_data: 'No data',
		user_detail_personal_information: 'Personal Information',
		user_detail_review_description: 'Review detailed account information of the selected user.',
		user_detail_no_user_data: 'No user data.',

		// Priority
		// Status labels
		Pending: 'Pending',
		Resolved: 'Resolved',

		// Priority
		high: 'High',
		medium: 'Medium',
		low: 'Low',

		// page
		to: 'to',
		of: 'of',
		page: 'Page',

		// Delete Post Modal
		delete_post_title: 'Delete Post',
		delete_post_message: 'Are you sure you want to delete this post?',

		// postRequests
		postRequests: 'Post Requests',
		reject_post: 'Reject Post',
		reject_post_message: 'Are you sure you want to reject this post?',
		enter_reason: 'Enter rejection reason...',
		post_approved_success: 'Post approved successfully',
		post_rejected_success: 'Post rejected successfully',
		reject_button: 'Reject',
		progressing: 'Processing',

		// Reports Page
		reports: 'Reports',
		title_report: 'Post content',
		manage_reports: 'Handle violation reports from users',
		search_reports: 'Search by post content...',
		reporter: 'Reporter',
		reason: 'Reason',
		report_image: 'Image',
		time: 'Time',
		resolve: 'Resolve',
		resolved: 'Resolved',
		completed: 'Completed',
		newest: 'Newest',
		oldest: 'Oldest',
		sort_date: 'Date',
		sort_name: 'Name',
		report_resolved: 'Report resolved successfully',
		report_resolved_desc: 'Report has been marked as completed',
		confirm_delete_title: 'Confirm deletion',
		confirm_delete_desc: 'Are you sure you want to delete this report?',
		no_image: 'No image',
		no_reports_found: 'Reports not found',
		report_post: 'Posts',
		report_comment: 'Comment',
		ban_confirm_comment: 'Are you sure you want to ban this comment?',
		ban_success: 'Comment banned successfully',
		hide: 'Hide Comment',
		hide_confirm_comment:
			'Are you sure you want to hide this comment and mark the report as resolved?',
		hide_success: 'Comment hidden successfully',
		hide_and_resolved_success: 'Comment hidden and report marked as resolved',
		report_status_updated: 'Status updated successfully',
		no_reports: 'No reports',
		showing_range: 'Showing',

		// blogs
		author: 'Author Name',
		title: 'Title',
		manage_blogs: 'Manage knowledge blogs',
		search_blogs: 'Search blogs...',
		confirm_delete_blog: 'Are you sure you want to delete this blog?',
		delete_warning: 'This action cannot be undone!',

		// stages
		stages: 'Stages',
		stage_management: 'Stage Management',
		stage_subtitle: 'Create, edit, search, and sort stages.',
		stage_sort_time: 'Sort by time',
		stage_add: 'Add stage',
		stage_update: 'Update stage',
		stage_modal_hint: 'Provide a title and description for the stage.',
		stage_title: 'Title',
		stage_description: 'Description',
		stage_title_placeholder: 'Enter stage title',
		stage_description_placeholder: 'Describe the stage',
		stage_time: 'Time',
		stage_order: 'No.',
		stage_search_placeholder: 'Search by title or description',
		stage_confirm_delete: 'Are you sure you want to delete this stage?',
		stage_delete_success: 'Stage deleted',
		stage_delete_fail: 'Cannot delete stage',
		stage_delete_note: 'This will remove the stage from the list.',
		stage_create_success: 'Stage created',
		stage_update_success: 'Stage updated',
		stage_fetch_fail: 'Cannot load stages',
		stage_action_fail: 'Action failed',
		stage_title_required: 'Please enter a stage title',
		stage_description_required: 'Please enter a stage description',
		loading: 'Loading...',
		checking: 'Checking...',
		no_data: 'No data',

		// type
		types: 'Types',
		product_types: 'Durian Types',
		manage_product_types: 'Manage durian types',
		add_product_type: 'Add durian type',
		product_type: 'Durian Type',
		description: 'Description',
		created_date: 'Created Date',
		no_description: 'No description',
		no_product_types: 'No durian types found',
		search_product_types: 'Search by durian type name, description...',
		enter_product_type_name: 'Enter durian type name',
		product_type_name: 'Durian Type Name',
		enter_description: 'Enter description',
		type_description_template: 'Origin: ...\nCharacteristics: ...\nAdvantages: ...\nHarvest time: ...',
		edit_product_type: 'Edit durian type',
		confirm_delete_product_type: 'Are you sure you want to delete this durian type?',
		create: 'Create',
		creating: 'Creating...',
		update: 'Update',
		updating: 'Updating...',
		deleting: 'Deleting...',
		unknown_date: 'Unknown date',
		invalid_date: 'Invalid date',
		// Toast messages
		type_name_required: 'Durian type name is required',
		type_name_duplicate: 'Durian type name already exists',
		type_description_required: 'Description is required',
		create_type_success: 'Durian type created successfully',
		create_type_failed: 'Failed to create durian type',
		update_type_success: 'Durian type updated successfully',
		update_type_failed: 'Failed to update durian type',
		delete_type_success: 'Durian type deleted successfully',
		delete_type_failed: 'Failed to delete durian type',
		fetch_type_failed: 'Failed to load durian types',
		// Pagination
		page: 'Page',
		previous: 'Previous',
		next: 'Next',

		// Phone validation
		phone_error_required: 'Phone number is required',
		phone_error_invalid: 'Invalid phone number (must be 10 digits, starting with 03, 05, 07, 08, 09)',

		// Password rules display
		profile_pw_rules_title: 'Password requirements:',
		profile_pw_rule1: 'At least 12 characters',
		profile_pw_rule2: 'At least one uppercase letter',
		profile_pw_rule3: 'At least one lowercase letter',
		profile_pw_rule4: 'At least one number',
		profile_pw_rule5: 'At least one special character (e.g. @, #, $)',

		// Password feedback
		profile_pw_match: 'Passwords match',
		profile_pw_not_match: 'Passwords do not match',
		profile_pw_same_as_current: 'New password must differ from current password',

		// Password error messages from server
		profile_pw_wrong_current: 'Current password is incorrect!',
		profile_pw_invalid_new: 'New password is invalid!',
		profile_pw_server_error: 'Server error! Please try again later.',
	},
};

const LanguageContext = createContext(undefined);

export function LanguageProvider({ children }) {
	const [language, setLanguage] = useState('vi');

	const t = (key) => {
		const value = translations[language]?.[key];
		return value || key;
	};

	return (
		<LanguageContext.Provider value={{ language, setLanguage, t }}>
			{children}
		</LanguageContext.Provider>
	);
}

export function useLanguage() {
	const context = useContext(LanguageContext);
	if (!context) {
		throw new Error('useLanguage must be used within a LanguageProvider');
	}
	return context;
}
