import express from "express";

import { authRoute } from "@/routes/authRoute";
import { profileRoute } from "@/routes/profileRoute";
import { productRoute } from "@/routes/productRoute";
import { adminProductRoute } from "@/routes/adminProductRoute";
import { ratingRoute } from "@/routes/ratingRoute";
import { typeProductRoute } from "@/routes/typeProductRoute";
import { stepRoute } from "@/routes/stepRoute";
import { blogRoute } from "@/routes/blogRoute";
import { postRoute } from "@/routes/postRoute";
import { commentPostRoute } from "@/routes/commentPostRoute";
import { reactionCommentRoute } from "@/routes/reactionCommentRoute";
import { reportPostRoute } from "@/routes/reportPostRoute";
import { diaryRoute } from "@/routes/diaryRoute";
import { favoriteRoute } from "@/routes/favoriteRoute";
import { gardenRoute } from "@/routes/gardenRoute";
import { chatRoute } from "@/routes/chatRoute";
import { notificationRouter } from "@/routes/notificationRoute";
import { permissionRoute } from "@/routes/permissionRoute";
import { userRoute } from "@/routes/userRoute";
import { serviceProviderProfileRoute } from "@/routes/serviceProviderProfileRoute";
import { reportCommentRoute } from "@/routes/reportCommentRoute";
import { messageRoute } from "@/routes/messageRoute";
import { aiRoute } from "@/routes/aiRoute";

const Router = express.Router();

Router.use("/auth", authRoute);
Router.use("/user", userRoute);
Router.use("/profile", profileRoute);
Router.use("/products", productRoute);
Router.use("/admin/products", adminProductRoute);
Router.use("/ratings", ratingRoute);
Router.use("/type-product", typeProductRoute);
Router.use("/step", stepRoute);
Router.use("/blog", blogRoute);
Router.use("/post", postRoute);
Router.use("/report", reportPostRoute);
Router.use("/comment", commentPostRoute);
Router.use("/reaction", reactionCommentRoute);
Router.use("/diary", diaryRoute);
Router.use("/favorite", favoriteRoute);
Router.use("/garden", gardenRoute);
Router.use("/notification", notificationRouter);
Router.use("/permission", permissionRoute);
Router.use("/capability-profile", serviceProviderProfileRoute);
Router.use("/report-comment", reportCommentRoute);
Router.use("/messages", messageRoute);
Router.use("/ai", aiRoute);

export const API_v1 = Router;
