service: vietdurian-nodejs-service # Name of your service
useDotenv: true
provider:
  name: aws
  runtime: nodejs22.x # Use a current Node.js version, e.g., nodejs20.x or nodejs18.x
  timeout: 900 # Set timeout to 15 minutes (900 seconds) for long-running processes
  memorySize: 1024 # Set memory to 2048 MB for better performance
  stage: prod
  region: ap-southeast-1
  environment:
    NODE_ENV: production
    AUTHOR: ${env:AUTHOR}
    MONGODB_URI: ${env:MONGODB_URI}
    MONGODB_URI_ATLAS: ${env:MONGODB_URI_ATLAS}
    DATABASE_NAME: ${env:DATABASE_NAME}
    DISPLAY_HOST: ${env:DISPLAY_HOST}
    HOST: ${env:HOST}
    PORT: ${env:PORT}
    AI_SERVICE_URL: ${env:AI_SERVICE_URL}
    UPSTASH_REDIS_URL: ${env:UPSTASH_REDIS_URL}
    ACCESS_TOKEN_SECRET: ${env:ACCESS_TOKEN_SECRET}
    REFRESH_TOKEN_SECRET: ${env:REFRESH_TOKEN_SECRET}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    CLOUDINARY_API_SECRET: ${env:CLOUDINARY_API_SECRET}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}
    YOUR_GOOGLE_CLIENT_ID: ${env:YOUR_GOOGLE_CLIENT_ID}
    YOUR_GOOGLE_CLIENT_SECRET: ${env:YOUR_GOOGLE_CLIENT_SECRET}
    GMAIL_USER: ${env:GMAIL_USER}
    GMAIL_PASS: ${env:GMAIL_PASS}
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
    GEMINI_MODEL: ${env:GEMINI_MODEL}
    GEMINI_GUARD_API_KEY: ${env:GEMINI_GUARD_API_KEY}
    GEMINI_GUARD_MODEL: ${env:GEMINI_GUARD_MODEL}
    DEBUG_AI_GUARD: ${env:DEBUG_AI_GUARD}
    AI_GUARD_BYPASS_ON_QUOTA: ${env:AI_GUARD_BYPASS_ON_QUOTA}

  iam:
    role: arn:aws:iam::867490540757:role/lambda_role

build:
  esbuild: false

plugins:
  - serverless-esbuild

package:
  patterns:
    - src/routes/**
    - src/model/**
    - src/config/swagger.js

functions:
  app:
    handler: src/server.handler # The file (server.js) and the exported handler (handler)
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}' # For all other routes

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    platform: node
    target: node22
    format: cjs
    keepNames: true
    alias:
      "@": ./src
    external:
      - aws-sdk

  