# serverless.yml
service: vietdurian-websocket

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  environment:
    STAGE: ${sls:stage}
    MONGODB_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource:
            - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*"

functions:
  connect:
    handler: handlers/connect.handler
    events:
      - websocket:
          route: $connect
          authorizer:
            name: wsAuthorizer
            identitySource: route.request.querystring.token

  disconnect:
    handler: handlers/disconnect.handler
    events:
      - websocket:
          route: $disconnect

  default:
    handler: handlers/default.handler
    events:
      - websocket:
          route: $default

  getOnlineUsers:
    handler: handlers/getOnlineUsers.handler
    events:
      - websocket:
          route: getOnlineUsers

  getUserConversations:
    handler: handlers/getUserConversations.handler
    events:
      - websocket:
          route: getUserConversations

  getConversationDetails:
    handler: handlers/getConversationDetails.handler
    events:
      - websocket:
          route: getConversationDetails

  sendMessage:
    handler: handlers/sendMessage.handler
    events:
      - websocket:
          route: sendMessage

  updateMessage:
    handler: handlers/updateMessage.handler
    events:
      - websocket:
          route: updateMessage

  deleteMessage:
    handler: handlers/deleteMessage.handler
    events:
      - websocket:
          route: deleteMessage

  getAllConversations:
    handler: handlers/getAllConversations.handler
    events:
      - websocket:
          route: getAllConversations

  wsAuthorizer:
    handler: handlers/authorizer.handler

plugins:
  - serverless-offline
  - serverless-dotenv-plugin