@startuml 85_viewPostList
skinparam shadowing false
skinparam sequenceArrowThickness 1
hide footbox

actor Farmer as "Users"
boundary HomePage as UI 
control notificationController as Controller 
participant ":notificationService" as Service 
participant ":notificationModel" as Model 
database Database as DB 

activate Farmer
activate UI
Farmer -> UI : 1. Users click "Bell" icon

UI -> Controller : 2. Get notifications list request
activate Controller

Controller -> Service : 3. getNotifications(userId)
activate Service
Service -> Model : 4. find(query)
activate Model
Model -> DB : 5. Execute query
activate DB
DB --> Model : 6. Return result
deactivate DB
Model --> Service : 7. Return notification list
deactivate Model
    Service -> Service : 8. check notification list
activate Service
deactivate Service
alt Notification available:
    Service --> Controller : 8.1 Return notification list
    Controller --> UI : 8.1.1 Show notification list
    UI --> Farmer : 8.1.2 Display notification list
else No notifications:
    Service --> Controller : 8.2 Return empty list
    deactivate Service
    Controller --> UI : 8.2.1 Show empty notification
    deactivate Controller
    UI --> Farmer : 8.2.2 Display 'Không có thông báo'
    deactivate UI
    deactivate Farmer
end
@enduml