@startuml 13.1_createProduct
hide footbox

actor User as "Users"
boundary "ProductPage" as View
control "ProductController" as Controller
participant ":ProductService" as Service
entity "ProductModel" as Model
database Database as Database


User -> View : 1. Input product fields
activate User
activate View
User -> View : 2. Submit product form
View -> View : 3. Validate input

opt Check validation
View --> User : 3.1. Show validation error
end

    View -> Controller : 4. POST /products/add
    activate Controller

    Controller -> Service : 5. createProduct()
    activate Service

alt Product exists
    Service -> Model : 6.1. checkNameConflict()
    activate Model

    Model -> Database : 6.1.1. findOne({ name })
    activate Database
    Database --> Model : 6.1.2. Return result (true/false)
    deactivate Database

    Model --> Service : 6.1.3. Return conflict state
    deactivate Model

        Service --> Controller : 6.1.4. Return error: product already exists
        Controller --> View : 6.1.5. Return error response
        View --> User : 6.1.6. Show error
    else Product is valid
        Service -> Model : 6.2. Save new product
        activate Model

        Model -> Database : 6.2.1. insertOne()
        activate Database
        Database --> Model : 6.2.2. Created
        deactivate Database

        Model --> Service : 6.2.3. Return created entity
        deactivate Model

        Service --> Controller : 6.2.4. Return product data
        deactivate Service
        Controller --> View : 6.2.5. Return 200 OK + product data
        deactivate Controller
        View --> User : 6.2.6. Show success
        deactivate View
deactivate User
    end


@enduml