@startuml 146_createDiaryStep
skinparam monochrome true
skinparam shadowing false
skinparam sequenceArrowThickness 1
hide footbox

actor User as "Farmer"
boundary DiaryDetailPage as UI
 
control diaryController as Controller
participant ":diaryService" as Service
participant ":diaryStepModel" as Model
database Database as DB

User -> UI : 1. Click "Add Diary Step" button
activate User
activate UI
UI -> UI : 2. Display diary step form
activate UI
deactivate UI
User -> UI : 3. Enter name, description, cost, image
User -> UI : 4. Click submit button
UI -> UI : 5. Validate input
activate UI
deactivate UI
opt Invalid Input or fields left empty
    UI --> User : 5.1 Display error message
end
UI -> Controller : 6. Create diary step request
activate Controller
Controller -> Service : 7. addDiaryStep(data, diaryId)
activate Service
Service -> Model : 8. save(data)
activate Model
Model -> DB : 9. Execute insert query
activate DB
DB --> Model : 10. Return result
deactivate DB
Model --> Service : 11. Return insert result
deactivate Model
Service -> Service : 12. check insert result
activate Service
deactivate Service

alt Create diary step successful
    Service --> Controller : 12.1 Return DiaryResponse
    Controller --> UI : 12.1.1 Return response
    UI --> User : 12.1.2 Redirect to diary page with new diary
else Create diary step failed
    Service --> Controller : 12.2 Return error
    deactivate Service
    Controller --> UI : 12.2.1 Return error response
    deactivate Controller
    UI --> User : 12.2.2 Display error message
    deactivate UI
    deactivate User
end

@enduml
