@startuml 16.1_createCommentBlog
hide footbox
title Create Comment Post
actor User as "Users"
boundary CommentPostPage as View
control CommentPostRoute as Route
participant ":AuthMiddleware" as Middleware
control "CommentPostController" as Controller
participant ":CommentPostService" as Service
participant ":CommentPostModel" as Model
database Database as Database


User -> View : 1. Input comment content
activate View
activate User
View -> View : 2. Validate input

opt Check validation
    View --> User : 2.1. Show validation error
end

    View -> Route : 3. POST /api/v1/comment
    activate Route

    Route -> Middleware : 4. AuthenticateUser(req, res, next)
    activate Middleware
    ref over User, Database : Verifies token
    Middleware -> Controller : 5. Forward CreateCommentBlogRequest
    deactivate Middleware
    activate Controller

    Controller -> Service : 6. Process comment creation
    activate Service

alt Comment already exists / duplicated
    Service -> Model : 7.1. Check conflicts
    activate Model

    Model -> Database : 7.1.1. Check existing comment
    activate Database
    Database --> Model : 7.1.2. Conflict result\n(true / false)
    deactivate Database

    Model --> Service : 7.1.3. Return conflict state
    deactivate Model

        Service --> Controller : 7.1.4. Return comment already exists
        Controller --> Route : 7.1.5. Return error response
        Route --> View : 7.1.6. Show error
else Comment is valid
        Service -> Model : 7.2. Save new comment
        activate Model

        Model -> Database : 7.2.1. Persist comment data
        activate Database
        Database --> Model : 7.2.2. Created
        deactivate Database

        Model --> Service : 7.2.3. Return created entity
        deactivate Model

        Service --> Controller : 7.2.4. Return CommentBlogResponse
        deactivate Service
        Controller --> Route : 7.2.5. Return 200 OK + comment data
        deactivate Controller
        Route --> View : 7.2.6. Show success
        deactivate Route
end

View --> User : 8. Display form result (success or error)
deactivate View
deactivate User
@enduml
