@startuml CreateReport

actor User as "Users"
boundary "BlogPage" as View 
participant ":reportBlogRoute" as Route 
control "authMiddleware" as Auth 
control "reportBlogController" as Controller 
participant ":reportBlogService" as Service 
entity "reportBlogModel" as Model 
database "MongoDB" as MongoDB 
hide footbox

    User -> View: 1. Click "Report" icon 
    activate User
    activate View

    View -> View: 2. Show report modal
    activate View
    deactivate View
        opt User cancels
        View --> User: 2.1. Cancel report
    end

    User -> View: 3. Enter report reason and Submit
    View -> View: 4. Validate input
    activate View
    deactivate View
    opt Invalid Input
        View --> User: 4.1. Display "Reason is required shortest 10 characters."
    end

    View -> Route: 5. POST /api/v1/report { blogId, userId, reason }
    activate Route
    Route -> Auth: 6. authenticateUser(req, res, next)
    activate Auth
    ref over User, MongoDB : Verifies token

    Auth -> Controller: 7. next(req)
    deactivate Auth
    activate Controller

    Controller -> Service: 8. createReport(reportData)
    activate Service

    Service -> Model: 9. insertOne(reportData)
    activate Model

    Model -> MongoDB: 10. Insert new report
    activate MongoDB
    MongoDB --> Model: 11. Return created report
    deactivate MongoDB

    Model --> Service: 12. Return result
    deactivate Model

    Service --> Controller: 13. Return created report
    deactivate Service

    Controller --> Route: 14. 201 Created + report
    deactivate Controller

    Route --> View: 15. Render created report
    deactivate Route

    View --> User: 16. Display created report
    deactivate View
    deactivate User


@enduml