@startuml CreateReport

actor User as "Users"
boundary "BlogPage" as View #lightblue
participant ":reportRoute" as Route #lightblue
control "authMiddleware" as Auth #Orange
control "reportController" as Controller #lightblue
participant ":reportService" as Service #lightblue
entity "reportModel" as Model #lightblue
database "MongoDB" as MongoDB #yellow

    User -> View: 1. Click "Report" icon 
    activate User
    activate View

    View -> View: 2. Show report modal
    activate View
    deactivate View
        opt User cancels
        View --> User: 2.1. Cancel report
    end

    User -> View: 3. Enter report reason and Submit
    View -> View: 3. Validate input
    activate View
    deactivate View
    opt Invalid Input
        View --> User: 3.1. Display "Reason is required shortest 10 characters."
    end

    View -> Route: 4. POST /api/v1/report { blogId, userId, reason }
    activate Route
    Route -> Auth: 5. authenticateUser(req, res, next)
    activate Auth
    ref over User, View, Route, Auth, Controller, Service, Model, MongoDB : 6. Middleware verifies access token


    Auth --> Route: 7. authentication success
    deactivate Auth

    Route -> Controller: 8. createReport(req.body, req.user)
    activate Controller

    Controller -> Service: 9. createReport(reportData)
    activate Service

    Service -> Model: 10. createReport(reportData)
    activate Model

    Model -> MongoDB: 11. Insert new report
    activate MongoDB
    MongoDB --> Model: 12. Return created report
    deactivate MongoDB

    Model --> Service: 13. Return result
    deactivate Model

    Service --> Controller: 14. Return created report
    deactivate Service

    Controller --> Route: 15. 201 Created + report
    deactivate Controller

    Route --> View: 16. Render created report
    deactivate Route

    View --> User: 17. Display created report
    deactivate View
    deactivate User


@enduml