@startuml ViewReportList

actor Admin
boundary "AdminDashboard" as View
participant ":reportPostRoute" as Route
control ":authMiddleware" as Auth
control "reportPostController" as Controller 
participant ":reportPostService" as Service 
entity "reportPostModel" as Model 
database "MongoDB" as MongoDB 
hide footbox

Admin -> View: 1. Click "Report Management"
activate Admin
activate View

View -> Route: 2. GET /api/v1/report
activate Route

Route -> Auth: 3. authenticateUser(req, res, next)
activate Auth
ref over Admin, MongoDB : Verifies token


Auth -> Controller: 4. next(req)
deactivate Auth
activate Controller

Controller -> Service: 5. getAllReport()
activate Service

Service -> Model: 6. find()
activate Model
Model -> MongoDB: 7. Query all reports
activate MongoDB
MongoDB --> Model: 8. Return report list
deactivate MongoDB
Model --> Service: 9. Return report list
deactivate Model

Service --> Service: 10. checkEmptyResult()
activate Service
deactivate Service

alt Reports available
    Service --> Controller: 10.1. Return reports
    Controller --> Route: 10.1.1. Return 200 OK 
    Route --> View: 10.1.2. Render report list
    View --> Admin: 10.1.3. Show reports with user & Blog details
else Report list empty
    Service --> Controller: 10.2. Return empty result
    deactivate Service
    Controller --> Route: 10.2.1. Return 200 OK 
    deactivate Controller
    Route --> View: 10.2.2. Show "Report list is empty"
    deactivate Route
    View --> Admin: 10.2.3. Display empty list message
    deactivate View
    deactivate Admin
end
@enduml
