@startuml 1_register
hide footbox

actor User as "Users"
boundary "RegisterPage" as View
control "AuthController" as Controller
control "OtpController" as OtpController
participant ":AuthService" as Service
participant ":SmsService" as SmsService
entity "UserModel" as Model
database Database as Database
participant ":SmsAPI" as SmsAPI

User -> View : 1. Input register fields
activate User
activate View
User -> View : 2. Submit register form


View -> View : 3. Validate input
activate View
deactivate View

opt Empty or mailformed information
    View --> User : 2.1. Return message
end

View -> Controller : 3. POST /auth/register
activate Controller

Controller -> Service : 4. register()
activate Service


Service -> Model : 5. findByEmail()
activate Model

Model -> Database : 6. findOne()
activate Database
Database --> Model : 7. Return user (or null)
deactivate Database

Model --> Service : 8. Return user (or null)
deactivate Model

Service -> Service : 9. checkEmailUnique()
activate Service
deactivate Service

alt User already exists
    Service --> Controller : 9.1. Return error: email already exists
    Controller --> View : 9.1.1. Return error
    View --> User : 9.1.2. Display error: email already exists

else User does not exist
    Service -> Model : 9.2.2. createAccount(is_verified=false)
    activate Model
    Model -> Database : 9.2.3. insertOne()
    activate Database
    Database --> Model : 9.2.4. Return insert result
    deactivate Database
    Model --> Service : 9.2.5. Return account created
    deactivate Model
    Service --> Controller : 9.2.6. Return success
    deactivate Service

    Controller -> OtpController : 9.2.8. sendOtp()

    activate OtpController

    OtpController -> SmsService : 9.2.9. sendOtp()
    activate SmsService

    SmsService -> SmsService: 9.2.10. generateOtp()
    activate SmsService
    deactivate SmsService    

    SmsService -> SmsAPI: 9.2.11. sendSms()
    activate SmsAPI
    SmsAPI --> SmsService: 9.2.12. Return SMS API response
    deactivate SmsAPI
    SmsService -> SmsService: 9.2.13. saveOtpToCache()
    activate SmsService
    deactivate SmsService
    SmsService --> OtpController: 9.2.14. Return OTP
    OtpController --> Controller: 9.2.15. Return OTP
    deactivate OtpController
        Controller --> View: 9.2.15. Return OTP
    deactivate Controller

    View --> User: 9.2.16. Display OTP modal
    User -> View: 9.2.17. inputOtp()
    View -> View: 9.2.18. Check form valid
    activate View
    deactivate View

    opt Empty or mailformed information
    View --> User : 9.2.18.1. Display validation error
    end

    View -> OtpController: 9.2.19. POST /otp/verify
    activate OtpController
    OtpController -> SmsService: 9.2.20. verifyOtp()
    SmsService -> SmsService: 9.2.21. checkOtpInCache()
    activate SmsService
    deactivate SmsService

alt Otp does not match
    SmsService --> OtpController : 9.2.22. Return false
    OtpController --> View : 9.2.22.1. Return error: OTP mismatch
    View --> User : 9.2.22.2. Display error: OTP mismatch

else Otp match
    SmsService --> OtpController : 9.2.23. Return true
    deactivate SmsService
    OtpController --> View : 9.2.23.1. Return verified
    OtpController -> Service : 9.2.23.2. updateVerificationStatus()
    activate Service
    Service -> Model : 9.2.23.3. setIsVerifiedTrue()
    activate Model
    Model -> Database : 9.2.23.4. updateOne()
    activate Database
    Database --> Model : 9.2.23.5. Return update result
    deactivate Database
    Model --> Service : 9.2.23.6. Return updated
    deactivate Model
    Service --> OtpController : 9.2.23.7. Return success
    deactivate Service


    OtpController --> View : 9.2.23.8. Return success
    deactivate OtpController
    View --> User : 9.2.24. Redirect to login page
        deactivate View
    deactivate User
end
end

@enduml
