@startuml View Reaction Comments

actor User as "Users"
boundary "BlogDetailPage" as View 
participant ":reactionRoute" as Route 
control "authMiddleware" as Auth 
control "reactionController" as Controller 
participant ":reactionService" as Service 
entity "reactionCommentModel" as Model 
entity "userModel" as UserModel 
database "MongoDB" as MongoDB
hide footbox

    User -> View: 1. Click a specific dish/icon reactions
    activate User
    activate View

    View -> Route: 2. GET /api/v1/reaction { commentId }
    activate Route
    Route -> Auth: 3. authenticateUser(req, res, next)
    activate Auth
    ref over User, MongoDB : Verifies token
    
    Auth -> Controller: 4. next(req)
    deactivate Auth
    activate Controller

    Controller -> Service: 5. getReactionsByCommentId(commentId)
    activate Service

    Service -> Model: 6. getReactionsByCommentId(commentId)
    activate Model

    Model -> UserModel: 7. populate reactions with user details
    activate UserModel

    UserModel -> MongoDB: 8. Query reactions for the comment
    activate MongoDB
    MongoDB --> UserModel: 9. Return queried reactions
    deactivate MongoDB

    UserModel --> Model: 10. Return populated reactions
    deactivate UserModel

    Model --> Service: 11. Return result
    deactivate Model

    Service --> Controller: 12. Return reactions data
    deactivate Service

    Controller --> Route: 13. Send 200 OK + reactions data
    deactivate Controller

    Route --> View: 14. Render reactions data
    deactivate Route

    View --> User: 15. Display reactions data
    deactivate View
    deactivate User


@enduml