@startuml UpdateReaction

actor User as "Users"
boundary "BlogDetailPage" as View 
participant ":reactionRoute" as Route 
control "authMiddleware" as Auth 
control "reactionController" as Controller 
participant ":reactionService" as Service 
entity "reactionCommentModel" as Model
database "MongoDB" as MongoDB 
hide footbox

    User -> View: 1. Hover reaction icon
    activate User
    activate View

    View -> View: 2. Show icon list
    activate View
    deactivate View

    opt Cancel Update
        View --> User: 2.1. Move cursor away
    end

    User -> View: 3. Select a reaction type

    View -> Route: 4. PATCH /api/v1/reaction { reactionId, reactionType }
    activate Route
    Route -> Auth: 5. authenticateUser(req, res, next)
    activate Auth
    ref over User, MongoDB : Verifies token
    Auth --> Route: 6. authentication success
    deactivate Auth

    Route -> Controller: 7. updateReaction(req, res)
    activate Controller

    Controller -> Service: 8. updateReaction(reactionData, userId)
    activate Service

    Service -> Model: 9. updateReaction(reactionData, userId)
    activate Model

    Model -> MongoDB: 10. Update existing reaction
    activate MongoDB
    MongoDB --> Model: 11. Return updated reaction
    deactivate MongoDB

    Model --> Service: 12. Return result
    deactivate Model

    Service --> Controller: 13. Return updated reaction
    deactivate Service

    Controller --> Route: 14. 200 OK + reaction
    deactivate Controller

    Route --> View: 15. Render updated reaction
    deactivate Route

    View --> User: 16. Display updated reaction by the comment
    deactivate View
    deactivate User

@enduml