@startuml UpdateReaction

actor User as "Users"
boundary "BlogDetailPage" as View 
participant ":reactionRoute" as Route 
control "authMiddleware" as Auth 
control "reactionController" as Controller 
participant ":reactionService" as Service 
entity "reactionCommentModel" as Model
database "MongoDB" as MongoDB 
hide footbox

    User -> View: 1. Hover reaction icon
    activate User
    activate View

    View -> View: 2. Show icon list
    activate View
    deactivate View

    opt Cancel Update
        View --> User: 2.1. Move cursor away
    end

    User -> View: 3. Select a reaction type

    View -> Route: 4. PATCH /api/v1/reaction { reactionId, reactionType }
    activate Route
    Route -> Auth: 5. authenticateUser(req, res, next)
    activate Auth
    ref over User, MongoDB : Verifies token

    Auth -> Controller: 6. next(req)
    deactivate Auth
    activate Controller

    Controller -> Service: 7. updateReaction(reactionData, userId)

    activate Service

    Service -> Model: 8. findByIdAndUpdate(reactionData, userId)
    activate Model

    Model -> MongoDB: 9. Update existing reaction
    activate MongoDB
    MongoDB --> Model: 10. Return updated reaction
    deactivate MongoDB

    Model --> Service: 11. Return result
    deactivate Model

    Service --> Controller: 12. Return updated reaction
    deactivate Service

    Controller --> Route: 13. 200 OK + reaction
    deactivate Controller

    Route --> View: 14. Render updated reaction
    deactivate Route

    View --> User: 15. Display updated reaction by the comment
    deactivate View
    deactivate User

@enduml