@startuml Delete

actor User as "Users"
boundary "BlogDetailPage" as View 
participant ":reactionRoute" as Route
control "authMiddleware" as Auth 
control "reactionController" as Controller 
participant ":reactionService" as Service 
entity "reactionCommentModel" as Model 
database "MongoDB" as MongoDB 
hide footbox

    User -> View: 1. Click reaction icon of yourself
    activate User
    activate View


    View -> Route: 2. DELETE /api/v1/reaction { reactionId }
    activate Route
    Route -> Auth: 3. authenticateUser(req, res, next)
    activate Auth
    ref over User, MongoDB : Verifies token

    Auth -> Controller: 4. next(req)
    deactivate Auth 
    activate Controller

    Controller -> Service: 5. deleteReaction(reactionId)
    activate Service

    Service -> Model: 6. findByIdAndDelete(reactionId)
    activate Model

    Model -> MongoDB: 7. Delete existing reaction
    activate MongoDB
    MongoDB --> Model: 8. Return deleted reaction
    deactivate MongoDB

    Model --> Service: 9. Return result
    deactivate Model

    Service --> Controller: 10. Return deleted reaction
    deactivate Service

    Controller --> Route: 11. 200 OK + reaction
    deactivate Controller

    Route --> View: 12. Render deleted reaction
    deactivate Route

    View --> User: 13. Update the interface
    deactivate View
    deactivate User


@enduml