@startuml ViewMessage

actor User as "Users"
boundary "ConversationDetailPage" as View 
participant ":chatRoute" as Route 
control "authMiddleware" as Auth 
control "chatController" as Controller
participant ":chatService" as Service 
entity "conversationModel" as ConvModel 
entity "messageModel" as MsgModel 
database "MongoDB" as MongoDB 
participant "Socket Server" as Socket 
hide footbox

    User -> View: 1. Open conversation (conversationId)
    activate User
    activate View

    View -> Route: 2. GET /api/v1/chat/user-conversations
    activate Route

    Route -> Auth: 3. authenticateUser(req, res, next)
    activate Auth
    
    ref over User, MongoDB : Verifies token
    Auth --> Route: 4. authentication success
    deactivate Auth

    Route -> Controller: 5. getDetailsConversation(req, res)
    deactivate Route
    activate Controller

    Controller -> Service: 6. getUserConversation(userId)
    activate Service

    Service -> ConvModel: 7. getUserConversation(userId, isRead = true)
    activate ConvModel

    ConvModel -> MongoDB: 8. ExecuteQuery()
    activate MongoDB
    MongoDB --> ConvModel: 9. return conversation with messages
    deactivate MongoDB

    ConvModel --> Service: 10. return conversation details
    deactivate ConvModel

    Service -> ConvModel: 11. update(conversationId, isRead = true)
    activate ConvModel

    ConvModel -> MongoDB: 12. ExecuteQuery()
    activate MongoDB
    MongoDB --> ConvModel: 13. return updated conversation
    deactivate MongoDB

    ConvModel --> Service: 14. return updated conversation
    deactivate ConvModel

    Service -> MsgModel: 15. updateStatusBulk(conversationId, 'seen')
    activate MsgModel

    MsgModel -> MongoDB: 16. ExecuteQuery()
    activate MongoDB
    MongoDB --> MsgModel: 17. Return update result
    deactivate MongoDB

    MsgModel --> Service: 18. Return update result
    deactivate MsgModel

    Service --> Controller: 19. Return conversation details
    deactivate Service

    Controller -> Controller: 20. checkMessagesExistence()
    activate Controller
    deactivate Controller

    par Emit to Other User
        Controller -> Socket: 20.1. Emit 'messages_seen' to other user
        activate Socket
        Socket --> View: 20.1.1. Broadcast to other user client
        deactivate Socket
    else Emit to Admin
        Controller -> Socket: 20.2. Emit 'messages_seen' to admin
        deactivate Controller
        activate Socket
        Socket --> View: 20.2.1. Broadcast to admin client
        deactivate Socket
    end

    View --> User: 21. Display messages & chat interface
    deactivate View
    deactivate User

@enduml
