@startuml RecallMessage

actor User as "Users"
boundary "ConversationDetailPage" as View 
participant ":chatRoute" as Route 
control "authMiddleware" as Auth 
control "chatController" as Controller 
participant ":chatService" as Service 
entity "messageModel" as Model 
database "MongoDB" as MongoDB 
participant "Socket Server" as Socket 
hide footbox

    User -> View: 1. Click recall specific message
    activate User
    activate View

    View -> View: 2. Show confirmation dialog
    activate View
    deactivate View

    opt Cancel Recall
        View --> User: 2.1. Cancel recall
    end

    User -> View: 3. Confirm recall

    View -> Route: 4. PUT /api/v1/chat/message/{messageId}
    activate Route

    Route -> Auth: 5. authenticateUser(req, res, next)
    deactivate Route
    activate Auth
    ref over User, MongoDB : Verifies token


    Auth -> Controller: 6. next(req)
    deactivate Auth
    deactivate Route
    activate Controller

    Controller -> Service: 7. deleteMessage(messageId)
    activate Service

    Service -> Model: 8. deleteMessage(messageId)
    activate Model

    Model -> MongoDB: 9. ExecuteQuery()
    activate MongoDB
    MongoDB --> Model: 10. return updated message
    deactivate MongoDB

    Model --> Service: 11. return updated message
    deactivate Model

    Service --> Controller: 12. return updated message
    deactivate Service

    Controller -> Controller: 13. checkRecipientRole(updatedMessage)
    activate Controller
    deactivate Controller

    par Emit to other user
        Controller -> Socket: 13.1. emit 'message_recalled' to other user
        activate Socket
        Socket --> View: 13.1.1. broadcast to other user client
        deactivate Socket
    else Emit to admin
        Controller -> Socket: 13.2. emit 'message_recalled' to admin
        deactivate Controller
        activate Socket
        Socket --> View: 13.2.1. broadcast to admin client
        deactivate Socket
    end

    View --> User: 14. display updated message with (recalled) label
    deactivate View
    deactivate User

@enduml
