@startuml 47_createType
hide footbox

actor User as "Admin" 
boundary TypeManagementPage as View
control "TypeController" as Controller
participant ":TypeService" as Service
entity "TypeModel" as Model
database Database as Database


User -> View : 1. Enter name, description & submit
activate View
activate User
View -> View : 2. Validate input
activate View
deactivate View
opt Invalid Input or fields left empty
    View --> User : 2.1. Display errors message
end

View -> Controller : 3. createTypeProduct(typeData)
activate Controller

Controller -> Service : 4. createTypeProduct(typeData)
activate Service

alt Type exists
        Service -> Model : 4.1. Check conflicts
        activate Model

        Model -> Database : 4.1.1. Check existing type
        activate Database
        Database --> Model : 4.1.2. Conflict result
        deactivate Database

        Model --> Service : 4.1.3. Return conflict state
        deactivate Model

        Service --> Controller : 4.1.4. Return type already exists
        Controller --> View : 4.1.5. Show error message
        View --> User : 4.1.6. Display "Type already exists" message
else Type is valid
        Service -> Model : 4.2. save(typeData)
        activate Model

        Model -> Database : 4.2.1. save new type
        activate Database
        Database --> Model : 4.2.2. Return result
        deactivate Database

        Model --> Service : 4.2.3. Return created entity
        deactivate Model

                alt Create type successful
                        Service --> Controller : 4.2.3.1. Return create type successful
                        Controller --> View : 4.2.3.2. Show success message "Create type successful."
                        View --> User : 4.2.3.3. Display success message
                else Create type failed
                        Service --> Controller : 4.2.3.a. Return TypeResponse
                        deactivate Service
                        Controller --> View : 4.2.3.b. Show error message
                        deactivate Controller
                        View --> User : 4.2.3.c. Display "Create type failed" message
                        deactivate View
                        deactivate User
                end
end
@enduml
