@startuml 70_updateBlog
skinparam shadowing false
skinparam sequenceArrowThickness 1
hide footbox

actor Farmer as "Content Expert"
boundary BlogPage as UI 
control blogController as Controller 
participant ":blogService" as Service 
participant ":knowledgeBlogModel" as Model 
database Database as DB 

Farmer -> UI : 1. Select and click the "Edit" icon .
activate Farmer
activate UI
UI -> UI : 2. Validate updated blog data.
activate UI
deactivate UI
opt Invalid Input or fields left empty
    UI --> Farmer : 2.1 Display 'Please fill all required fields correctly.'
end

UI -> Controller : 3. Update blog request
activate Controller

Controller -> Service : 4. updateKnowledgeBlog(data, blogId)
activate Service
Service -> Model : 5. findByIdAndUpdate(data, blogId)
activate Model
Model -> DB : 6. Execute query
activate DB
DB --> Model : 7. Return result
deactivate DB
Model --> Service : 8. Return updated blog
deactivate Model
    Service -> Service : 9. check updated blog
activate Service
deactivate Service
alt Update blog successful:
    Service --> Controller : 9.1 Return updated blog
    Controller --> UI : 9.1.1 Show updated blog
    UI --> Farmer : 9.1.2 Display 'Blog updated successfully'
else Update blog failed:
    Service --> Controller : 9.2 Return null
    deactivate Service
    Controller --> UI : 9.2.1 Show error message
    deactivate Controller
    UI --> Farmer : 9.2.2 Display 'Blog update failed'
    deactivate UI
    deactivate Farmer
end
@enduml